import serial
import time
import numpy as np
import sys
import io
from PIL import Image
import requests
import base64

# --- API Configuration ---
# Your Stability AI API Key:
STABILITY_API_KEY = "" 

# Stability AI Endpoint and Model 
STABILITY_API_URL = "https://api.stability.ai/v2beta/stable-image/generate/core"
STABILITY_MODEL = "stable-diffusion-xl" 

# --- Serial Configuration ---
COM_PORT = 'COM17' 
BAUD_RATE = 115200 
START_COMMAND = "START_IMAGE_TRANSFER\n" 

# --- LCD Image Dimensions ---
IMAGE_WIDTH = 320  
IMAGE_HEIGHT = 170  
EXPECTED_SIZE = IMAGE_WIDTH * IMAGE_HEIGHT * 2 

# --- User Input Prompt ---
PROMPT = "An epic fantasy landscape featuring a giant floating island and twin moons, highly detailed digital painting."


# -----------------------------------------------------------------------------
# *** THE GENERATION LOGIC (STABILITY AI - CONTENT-TYPE FIXED) ***
# -----------------------------------------------------------------------------
def generate_image_from_prompt(prompt, api_key):
    """
    Generates an image using the Stability AI API via the requests library.
    """
    print(f"\n[GENERATING IMAGE] Prompt: '{prompt}' using Stability AI...")
        
    try:
        headers = {
            "Accept": "image/*", 
            "Authorization": f"Bearer {api_key}"
        }

        # Stability AI requires multipart/form-data encoding. 
        # We must structure the data this way to satisfy the API.
        data = {
            "prompt": (None, prompt), # The prompt is a required field
            "output_format": (None, "jpeg"),
            "aspect_ratio": (None, "16:9"),
            "model": (None, STABILITY_MODEL)
        }

        # Make the API call, using the 'files' parameter for form-data encoding
        response = requests.post(
            STABILITY_API_URL,
            headers=headers,
            files=data, # CRITICAL FIX: Changed from 'data=data' to 'files=data'
            timeout=30  
        )

        if not response.ok:
            # Handle API errors
            print(f"--- ERROR: Stability AI Failed ---")
            print(f"HTTP Status: {response.status_code}")
            # Check for specific "out of credits" message
            if 'not authorized' in response.text.lower() or 'insufficient' in response.text.lower():
                print("API Response Error: Insufficient credits or Key may be invalid.")
            else:
                print(f"API Response Error: {response.text}")
            return None

        # The response.content is the raw image bytes
        image_bytes = response.content
        pil_image = Image.open(io.BytesIO(image_bytes))
        
        print("[GENERATING IMAGE] Image successfully generated by Stability AI.")
        return pil_image

    except Exception as e:
        print(f"--- ERROR: Image Generation Failed ---")
        print(f"Details: {e}")
        return None
# -----------------------------------------------------------------------------


def convert_to_rgb565_raw(pil_image):
    """Resizes and converts the PIL Image to raw 16-bit RGB565 binary data."""
    
    # 1. Resize the image to the exact LCD dimensions
    if pil_image.size != (IMAGE_WIDTH, IMAGE_HEIGHT):
        print(f"[CONVERSION] Resizing image from {pil_image.size} to {IMAGE_WIDTH}x{IMAGE_HEIGHT}")
        img_resized = pil_image.resize((IMAGE_WIDTH, IMAGE_HEIGHT), Image.Resampling.LANCZOS)
    else:
        img_resized = pil_image

    # 2. Convert to NumPy array
    img_rgb = img_resized.convert("RGB")
    np_array = np.array(img_rgb, dtype=np.uint8)
    
    R = np_array[:, :, 0]
    G = np_array[:, :, 1]
    B = np_array[:, :, 2]

    # 3. Convert 8-bit channels to 5-6-5 bits and pack into 16-bit integer
    rgb565 = (R.astype(np.uint16) >> 3) << 11 | \
             (G.astype(np.uint16) >> 2) << 5 | \
             (B.astype(np.uint16) >> 3)
             
    # 4. Convert the 16-bit array to raw bytes (Little Endian '<u2')
    raw_data = rgb565.astype('<u2').tobytes()
    
    if len(raw_data) != EXPECTED_SIZE:
        raise ValueError(f"Conversion failed: Expected {EXPECTED_SIZE} bytes, got {len(raw_data)}.")

    print(f"[CONVERSION] Success. Converted {len(raw_data)} bytes to RGB565.")
    return raw_data

def send_image_serial(raw_data):
    """Sends the raw binary data to the ESP32 via the serial port."""
    try:
        print(f"[SERIAL] Connecting to {COM_PORT} at {BAUD_RATE}...")
        
        ser = serial.Serial(COM_PORT, BAUD_RATE)
        ser.write_timeout = 1 
        time.sleep(2) 

        # STEP 1: Send the start command
        print(f"[SERIAL] Sending start command: {START_COMMAND.strip()}")
        ser.write(START_COMMAND.encode())
        time.sleep(0.5) 

        # STEP 2: Send raw image data
        print(f"[SERIAL] Streaming {len(raw_data)} bytes of image data...")
        
        bytes_sent = ser.write(raw_data)
        
        ser.close()

        if bytes_sent == EXPECTED_SIZE:
            print("--- SUCCESS ---")
            print("Image generated, converted, and transmitted successfully via Stability AI.")
        else:
            print(f"--- FAILURE --- (Only sent {bytes_sent} of {EXPECTED_SIZE})")

    except serial.SerialException as e:
        print("--- SERIAL CONNECTION ERROR ---")
        print(f"Could not open or write to port {COM_PORT}. Error: {e}")
    
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    
    # 1. Generate Image using Stability AI
    pil_image = generate_image_from_prompt(PROMPT, STABILITY_API_KEY)
    
    if pil_image:
        # 2. Convert to ESP32 RGB565 Raw Bytes
        try:
            raw_data_bytes = convert_to_rgb565_raw(pil_image)
            
            # 3. Stream to ESP32
            send_image_serial(raw_data_bytes)
            
        except ValueError as e:
            print(f"FATAL ERROR during conversion: {e}")
        
    else:
        print("Image generation failed. Aborting transfer.")